// Generated by scripts/images/build-card-image.mjs from the owner-supplied ZEV
// scene. Do not edit by hand; rerun the script.

export const CARD_IMAGE = {
  width: 800,
  height: 400,
  avif: "/zev/zev-device-card.avif",
  webp: "/zev/zev-device-card.webp",
  jpg: "/zev/zev-device-card.jpg",
};

export const ARRAY_IMAGE = {
  width: 900,
  height: 450,
  avif: "/zev/zev-array-card.avif",
  webp: "/zev/zev-array-card.webp",
  jpg: "/zev/zev-array-card.jpg",
};
