// Generated by scripts/images/build-jv-banner.mjs. Do not edit by hand.
// Responsive sources for the ZelionTech x Expofin joint-venture banner.

export const JV_BANNER = {
  // Whole composite, viewports from 640px up.
  desktop: {
    avif: "/images/jv/jv-banner-960.avif 960w, /images/jv/jv-banner-1440.avif 1440w, /images/jv/jv-banner-1933.avif 1933w",
    webp: "/images/jv/jv-banner-960.webp 960w, /images/jv/jv-banner-1440.webp 1440w, /images/jv/jv-banner-1933.webp 1933w",
    jpg: "/images/jv/jv-banner-960.jpg 960w, /images/jv/jv-banner-1440.jpg 1440w, /images/jv/jv-banner-1933.jpg 1933w",
    fallback: "/images/jv/jv-banner-1933.jpg",
    width: 1933,
    height: 813,
  },
  // Art-directed crop of the left part, viewports below 640px.
  mobile: {
    media: "(max-width: 639px)",
    avif: "/images/jv/jv-banner-mobile-640.avif 640w, /images/jv/jv-banner-mobile-960.avif 960w",
    webp: "/images/jv/jv-banner-mobile-640.webp 640w, /images/jv/jv-banner-mobile-960.webp 960w",
    jpg: "/images/jv/jv-banner-mobile-640.jpg 640w, /images/jv/jv-banner-mobile-960.jpg 960w",
    width: 960,
    height: 723,
  },
  // The figure sits in a max-w-6xl container (72rem) with 1rem side padding.
  sizes: "(min-width: 1280px) 1152px, calc(100vw - 2rem)",
  placeholder: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYAAoAPu1iqU2ppaOiMAgBMB2JQBdiZAPX/AaxaTSQIli0Js34AP6vu1WlBL9ZJnuzIVeIIVZ5VjyCV7P7++/sD6CbXcHUuSouCYDZN+hcah6SzaeSf+mNyHyX+Iivf35tR/7Czkcs+qGxsm7uaRUF0n5A+LuBYuno0grR7ITKUUTGsSseetnsCmkzAAAA",
};
