// Generated by scripts/images/build-jv-banner.mjs. Do not edit by hand.
// Responsive sources for the ZelionTech x Expofin joint-venture banner.

export const JV_BANNER = {
  avif: "/images/jv/jv-banner-960.avif 960w, /images/jv/jv-banner-1440.avif 1440w, /images/jv/jv-banner-1933.avif 1933w",
  webp: "/images/jv/jv-banner-960.webp 960w, /images/jv/jv-banner-1440.webp 1440w, /images/jv/jv-banner-1933.webp 1933w",
  jpg: "/images/jv/jv-banner-960.jpg 960w, /images/jv/jv-banner-1440.jpg 1440w, /images/jv/jv-banner-1933.jpg 1933w",
  fallback: "/images/jv/jv-banner-1933.jpg",
  width: 1933,
  height: 813,
  // The figure sits in a max-w-6xl container (72rem) with 1rem side padding.
  sizes: "(min-width: 1280px) 1152px, calc(100vw - 2rem)",
  placeholder: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoYAAoAPu1iqU2ppaQiMAgBMB2JQBdiP/wGpU8WJvEmI1cAAP6v93JIBIp31m4U+XbpfyFWeVY8glez/8e/XkzZmC+qTu+EsCHAG79R4kPENlMRcLWArj8tNUMBguQCNovBDxzIXyFlxiS8c7fvq6cAYkkzGYsdAsxrAy9Y5jyMTXrTFr5C2XWSVgod/AAA",
  glow: "data:image/webp;base64,UklGRpYBAABXRUJQVlA4IIoBAADwDQCdASpgACgAPpE6mEglo6KhNVQOqLASCUAXsYTRYhwugWndtYgu8y8xUK0NrI3REhTOv5xFXwrSDM2IBbmxm7a6S7q3RJekXAsIsXQBxZdI42SX1gu0wh/zBfJ9HDAf9IoVJMgXRNv8fjswx2N2Q4ndODFg7IAA/vpNezHgK7SmtXTSXu1PzCbrPpyPV4sHD6xNM7ELnnCi2utSUJaEaFEb5F/i9yCfqiqQ/fFvizrHIdSz0AcQfshNtQVHw3S00CDiMqJQ9pwQs0Fq2CKazZLLf4XsfiMwxp1TZBUfv86xBaVFhbypEzJBrz70+pYdqsVm5JIPGTHHisTDsaYcZAmgRxiF0tDyHFfHOSu1z9+Ps5TTxeZ3Mcyoei9XiWHFZDG8Zs9KIZoE5QkZyh48ImylG/QGH3BBdgNVRttW7HJTLXWLYh4vnkPf3AmjnPDgj0MIhe3megq0ThOrmnpRzOKi8kSY+yYmivgO6IQqXsyUCyQ/ebXXYaA3+KUp5zFlUirSbgHA14AA",
};
